service: serverless-typescript-example

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2

Resources:
  ToDoListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: to-do-list
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1